name: Build Electron App

on:
  push:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run make
      - uses: actions/upload-artifact@v3
        with:
          name: macOS-build
          path: out/make/**/*

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run make
      - uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: out/make/**/*

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run make
      - uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: out/make/**/*
