name: Release Electron App

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Build macOS
        run: npm run make

      - uses: actions/upload-artifact@v4
        with:
          name: mac-arm64
          path: out/make/**/*

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Build Windows
        run: npm run make

      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: out/make/**/*

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Build Linux
        run: npm run make

      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: out/make/**/*

  release:
    needs: [build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./dist

      - name: Show downloaded files
        run: ls -R ./dist

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
